In [7]:
import pandas as pd

In [76]:
data = pd.read_csv('loan (1).csv')

C:\Users\hamps\AppData\Local\Temp\ipykernel_15920\317358369.py:1: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('loan (1).csv')

In [77]:
data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599,5000,5000,4975.0,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN

In [78]:
null_values = [(x,data[x].isnull().mean()*100) for x in data]
null_df = pd.DataFrame(null_values,columns=['column_name','percentage'])
drop_cols = list(null_df[null_df['percentage']>50]['column_name'])
data.drop(drop_cols,axis=1,inplace=True)
unique=data.nunique()
unique=unique[unique.values==1]
data.drop(labels=list(unique.index),axis=1,inplace=True)
drop_column = ["id","member_id","url","zip_code"]
data.drop(labels=drop_column,axis=1,inplace=True)
print(data.shape,"rows & columns")
data['int_rate']=(data['int_rate'].str.strip('%').astype(float))
num_col=['loan_amnt','funded_amnt','funded_amnt_inv','installment','int_rate','annual_inc','dti']
data[num_col] = data[num_col].apply(pd.to_numeric)
data.head()

(39717, 41) rows & columns

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,pub_rec_bankruptcies
0,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,...,5833.84,5000.00,863.16,0.00,0.00,0.00,Jan-15,171.62,May-16,0.0
1,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,...,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,Sep-13,0.0
2,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,...,3005.67,2400.00,605.67,0.00,0.00,0.00,Jun-14,649.91,May-16,0.0
3,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,...,12231.89,10000.00,2214.92,16.97,0.00,0.00,Jan-15,357.48,Apr-16,0.0
4,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,...,3513.33,2475.94,1037.39,0.00,0.00,0.00,May-16,67.79,May-16,0.0

In [79]:
data.fillna(method='bfill',inplace=True)
data.fillna(method='ffill',inplace=True)

In [80]:
from sklearn.pipeline import Pipeline

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

In [82]:
def convert_to_class(a):
    if a == 'Fully Paid':
        return 0
    elif a == 'Current':
        return 0
    else:
        return 1

In [83]:
data['output'] = data['loan_status'].apply(convert_to_class)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in data.columns:
    if data[i].dtype == "O":
        data[i] = le.fit_transform(data[i])

In [84]:
x = data.drop(['loan_status','output'],axis=1)
y = data['output']

In [85]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=.70,random_state=45)

In [122]:
pipeline = Pipeline([('pca',PCA(n_components=7)),('std',StandardScaler()),('decision_tree',DecisionTreeClassifier())])

In [123]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('pca', PCA(n_components=7)), ('std', StandardScaler()),
                ('decision_tree', DecisionTreeClassifier())])

In [124]:
from sklearn.metrics import accuracy_score

In [125]:
accuracy_score(y_test,pipeline.predict(x_test))

0.9655924806982209